services:
  - name: age-gender-api
    ports:
      - port: 8000
        protocol: http
    env:
      - key: PORT
        value: 8000
    run: uvicorn app:app --host 0.0.0.0 --port $PORT
    build:
      command: pip install -r requirements.txt